import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import { useRecoilState } from "recoil";
import { modalState, postIdState } from "../atoms/modalAtom";
import Modal from "../components/Modal";
import Widgets from "../components/Widgets";

export default function Home({ trendingResults, followResults, providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [postId, setPostId] = useRecoilState(postIdState);

  if (!session) return <Login providers={providers} />;

  console.log(modalState);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto ">
        <Sidebar />
        <Feed
          isOpen={isOpen}
          setIsOpen={setIsOpen}
          postId={postId}
          setPostId={setPostId}
        />
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />
        {isOpen && (
          <Modal
            isOpen={isOpen}
            setIsOpen={setIsOpen}
            postId={postId}
            setPostId={setPostId}
          />
        )}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
